const cards = [
'Acidic Slime',
'AEtherize',
'AEtherspouts',
'Aluren',
'Arachnogenesis',
'Awakening Zone',
'Bane of Progress',
'Beastmaster Ascension',
'Benthic Infiltrator',
'Bident of Thassa',
'Blighted Agent',
'Cold-Eyed Selkie',
'Command Beacon',
'Command Tower',
'Counterspell',
'Cryptolith Rite',
'Crystalline Crawler',
'Cyclonic Rift',
'Deepchannel Mentor',
'Dream Fracture',
'Edric, Spymaster of Trest',
'Elusive Krasis',
'Elvish Visionary',
'Eternal Witness',
'Evolving Wilds',
'Ezuri, Claw of Progress',
'Fable of Wolf and Owl',
'Fathom Mage',
'Fertilid',
'Fog Bank',
'Forbid',
'Forest',
'Forgotten Ancient',
'Glen Elendra Archmage',
'Herald of Secret Streams',
'Heroic Intervention',
'Hinterland Harbor',
'Invisible Stalker',
'Island',
'Jhessian Infiltrator',
'Kaseto, Orochi Archmage',
'Kodama\'s Reach',
'Krosan Grip',
'Lifecrafter\'s Bestiary',
'Lightning Greaves',
'Llanowar Reborn',
'Master of Waves',
'Maze of Ith',
'Mosswort Bridge',
'Mycoloth',
'Nature\'s Will',
'One with Nature',
'Oran-Rief, the Vastwood',
'Overwhelming Stampede',
'Peel from Reality',
'Pir, Imaginative Rascal',
'Prime Speaker Zegana',
'Rapid Hybridization',
'Rashmi, Eternities Crafter',
'Reliquary Tower',
'Sakura-Tribe Elder',
'Simic Growth Chamber',
'Simic Guildgate',
'Simic Manipulator',
'Simic Signet',
'Slither Blade',
'Sol Ring',
'Sower of Temptation',
'Swiftfoot Boots',
'Temple of Mystery',
'Temple of the False God',
'Terramorphic Expanse',
'Thornwood Falls',
'Thought Vessel',
'Toothy, Imaginary Friend',
'Viral Drake',
'Vivid Creek',
'Vivid Grove',
'Vorel of the Hull Clade',
'Whelming Wave',
'Woodland Stream',
];

export default cards;
